### ISSUE TITLE
use captureStackTrace for v8

### ISSUE THREAD

**Issue by AoJ** [Raynos/error#12]
v8 engine support Error.captureStackTrace to shift stacktrace to real place where error created.

Do you accept a PR to add this feature for only node.js/io.js?

**Comment by mcmahonjohn** [comment]
If you have a pull request to address this, it will definitely be worth a look.

**Comment by Raynos** [comment]
I would have to read up on best practices for `Error.captureStackTrace` to find out how to use it.

**Comment by Raynos** [comment]
I tried this, it does not seem necessary
