### ISSUE TITLE
Don't require `assert` module

### ISSUE THREAD

**Issue by saebekassebil** [Raynos/error#14]
Hey Jake and thanks for this module.

I'd really like to use this module for some simple error throwing in different low-level modules, but since this module depends on "assert" and "util" sadly that's not really an option.

By requiring assert and util (I'm only bothered by assert, because I use the "typed" errors), browserify will bundle all its `builtins` and this is a total bummer for small modules.

Maybe we could just `throw` instead of `asserting`? I know the code would be a bit more messy, but in return it'd make it much more light-weight.

I could make a PR if you're interested?

**Comment by Raynos** [comment]
You can make a PR to inline `assert`.

https://github.com/nodejs/node/blob/v0.10.32-release/lib/assert.js#L91-L113

We should create `lib/assert.js` and vendor the subset of assert that we use.

actually, `assert` is too big.. let's just create a simple one-line helper called `assert` in the file.

**Comment by pcguru** [comment]
This repo seems broken. `assert` is required in `typed.js` but it is no longer mentioned in package.json.

Adding this library to a React Native app causes the bundler to say:

```
bundling failed: "Unable to resolve module `assert` from `C:\\projects\\ConnectedLeague\\node_modules\\error\\typed.js`: Module does not exist in the module **map**
```

**Comment by Raynos** [comment]
This module is mostly designed for usage in node.

Creating a smaller bundle is not really a goal here. I have removed the usage of `xtend` but I've kept `assert` around.
