### ISSUE TITLE
v7.0.2 is missing on github

### ISSUE THREAD

**Issue by shesek** [Raynos/error#18]
v7.0.2 is available on npm, but the latest version on the repo here is v7.0.1.

**Comment by Raynos** [comment]
I’ve probably lost 7.0.2.

Let me fetch the tarball and see if there’s any unpushed changes other then the version bump. I’ll publish 7.0.3 soon

**Comment by Raynos** [comment]
Yeah i checked, no changes, just didnt push the version commit.

**Comment by Raynos** [comment]
Published 7.1.0 and pushed the tag.
