### ISSUE TITLE
[Request/Question] TypeScript definitions

### ISSUE THREAD

**Issue by Gounlaf** [Raynos/error#23]
Hi,

Could you provide typescript definitions for your package?
Unfortunately I didn't found community definitions (on DefinitelyTyped/DefinitelyTyped), and I'm not enough skilled to create one (I can try but it would take time :x).

Thanks,

Regards.

**Comment by Raynos** [comment]
I might add `tsdocstandard` to this repo.

Please remind me in a few days :D

**Comment by Raynos** [comment]
I've started this in a PR https://github.com/Raynos/error/pull/24

**Comment by Raynos** [comment]
I merged the PR that adds type definitions and released `error@10.3.0`

**Comment by Gounlaf** [comment]
Thanks !

**Comment by Gounlaf** [comment]
Hi @Raynos,

I've installed version 10.3.0 but my IDE (WebStorm) is still complaining about not finding definitions (TS7016).
As a "provider" I understand you provide Types via tsdocstandard
As a "consumer" does I need to add something? (it might be not supported by WebStorm =/)

Thanks,

Regards.

**Comment by Raynos** [comment]
@Gounlaf 

Can you share the tsconfig.json for your project ?

**Comment by Raynos** [comment]
Types are provided by typescript btw.

Tsdocstandard is just a linter that makes it easier to add jsdoc to a js library and write type definitions.

**Comment by Gounlaf** [comment]
@Raynos sure, see below.

I use typescript 3.8.3 and also a minimal configuration of typescript-eslint

```json5
{
  "compilerOptions": {
    "target": "ES2019",
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "./build",
    "strict": true,
    "noImplicitAny": true,
    "alwaysStrict": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "baseUrl": "./src",
    "paths": {
      "@i/*": ["i/*"],
      "@have/*": ["have/*"],
      "@some/*": ["some/*"],
      "@modules/*": ["modules/*"],
      "@alias/*": ["alias/*"]
    },
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by Raynos** [comment]
It's quite frustrating that typescript does not type check the implementation of `error`.

I tried your tsconfig and added

```js
  "include": [
    "src/**/*",
    "node_modules/error"
  ],
```

Basically telling typescript that node_modules/error exists and it started type checking properly.

However now i have `build/node_modules/error` ...

**Comment by Raynos** [comment]
https://github.com/microsoft/TypeScript/issues/33136

**Comment by Raynos** [comment]
There's another important property in tsconfig.json

```
  "allowJs": true,
```

**Comment by Raynos** [comment]
Looks like another user found a similar workaround ( https://github.com/microsoft/TypeScript/issues/33136#issuecomment-578699134 )

**Comment by Gounlaf** [comment]
Hi,

Sorry for the delay.
Thanks for your answers; I still have not test yet, I will confirm here if it's OK with solution you gave me.
